---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	fetch_context(fetch_context)
	analyze_repo(analyze_repo)
	plan_curriculum(plan_curriculum)
	insert_all_days(insert_all_days)
	save_all_concepts(save_all_concepts)
	build_memory_context(build_memory_context)
	generate_concept_content(generate_concept_content)
	mark_concept_complete(mark_concept_complete)
	__end__([<p>__end__</p>]):::last
	__start__ --> fetch_context;
	analyze_repo --> plan_curriculum;
	build_memory_context --> generate_concept_content;
	fetch_context --> analyze_repo;
	generate_concept_content --> mark_concept_complete;
	insert_all_days --> save_all_concepts;
	mark_concept_complete -.-> build_memory_context;
	plan_curriculum --> insert_all_days;
	save_all_concepts -.-> build_memory_context;
	mark_concept_complete -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
